site_name: PCC-FECalc
nav:
  - Home: index.md
  - API Reference: api.md
  - Examples: examples.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
