site_name: PCC-FECalc
nav:
  - PCC-FECalc: index.md
  - Installation:
      - Instructions: installation/instructions.md
      - Modifications: installation/modifications.md
  - Examples:
      - Example 1: examples/example1.md
  - API docs: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
